style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  UnusedPrivateProperty:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  ThrowsCount:
    active: false

complexity:
  TooManyFunctions:
    active: false
  LongParameterList:
    active: false

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'
